version: "3.3"

services:
  car-service-base:
    build:
      context: .
    container_name: car-service-base
    volumes:
      - .:/app
    ports:
      - "80"
    environment:
      # Postgres connectivity
      - DB_USER_NAME=user
      - DB_HOST=car-service-mysql
      - DB_PORT=3306
      - DB_NAME=cars
      - DB_PASSWORD=password

  car-service-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'cars'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 15
    ports:
      - '3333:3306'
    tty: true

  db_data_init:
    extends: car-service-base
    container_name: db_data_init
    depends_on:
      car-service-mysql:
        condition: service_healthy
    command: ["python", "-m", "bin.db_seeder"]

  cars_service_task_1:
    extends: car-service-base
    container_name: cars_service_task_1
    depends_on:
      db_data_init:
        condition: service_completed_successfully
    command: ["python", "-m", "app.task1"]

  cars_service_task_2:
    extends: car-service-base
    container_name: cars_service_task_2
    depends_on:
      db_data_init:
        condition: service_completed_successfully
    command: ["python", "-m", "app.task2"]

  cars_service_task_3:
    extends: car-service-base
    container_name: cars_service_task_3
    command: ["python", "-m", "app.task3"]

    